language: php
sudo: required
dist: trusty

php:
  - 7.3

os: linux

before script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan jwt:secret

script:
  - vendor/bin/phpunit